; [pytest]
; pythonpath = app
; testpaths = tests
; asyncio_mode = auto
; python_files = test_*.py
; python_classes = Test*
; python_functions = test_*
; # asyncio_default_fixture_loop_scope = session
; # mock_use_standalone_module = true
; # env_files = .env.test
; filterwarnings =
;     ignore::DeprecationWarning
;     ignore::RuntimeWarning
